name: grant_park

profile: grant_park

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


seeds:
  # Builds seeds into '<your_schema_name>_raw'
  grant_park:
    +schema: raw

models:
  grant_park:
    # Materialize staging models as views, and marts as tables
    staging:
      +schema: stage
      +materialized: table
    landing:
      +schema: stage
      +materialized: view
    vault:
      +schema: vault
      +materialized: table
    inter:
      +schema: stage
      +materialized: view
    marts:
      +schema: mart
      +materialized: table
      +snowflake_warehouse: "demo_wh"
      +docs:
        node_color: "black"

vars:
  # The `high date` variable will be accessible in all resources
  high_date: '8888-12-31'
