rt_demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      warehouse: DEMO_WH
      schema: DEV
      database: RT_DEMO_DEV
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: ACCOUNTADMIN
      warehouse: DEMO_WH
      schema: PROD
      database: RT_DEMO_PROD
